/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIapp;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author m.m pc
 */
public class app extends javax.swing.JFrame {

    Universitaet uni = new Universitaet("TDU");

    /**
     * Creates new form HA6
     */
    public app() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LVAtap = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        MN = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Nachname = new javax.swing.JTextField();
        Adress = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        Geburtstag = new javax.swing.JTextField();
        Geburtsort = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Studentliste = new javax.swing.JTable();
        loascheS = new javax.swing.JButton();
        Addstudent = new javax.swing.JButton();
        Telefonnummer = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Fachbereich = new javax.swing.JTextField();
        Fehlertext = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        clear1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TCnummer = new javax.swing.JTextField();
        Dname = new javax.swing.JTextField();
        Dnachname = new javax.swing.JTextField();
        Akadimischeritel = new javax.swing.JTextField();
        Dadress = new javax.swing.JTextField();
        Dtelefon = new javax.swing.JTextField();
        Demail = new javax.swing.JTextField();
        Dgeburtstag = new javax.swing.JTextField();
        Dgeburtsort = new javax.swing.JTextField();
        Dloaschen = new javax.swing.JButton();
        Dhinzufugen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dtabel = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        Dfehlertext = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Did = new javax.swing.JTextField();
        clear2 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        LVcode = new javax.swing.JTextField();
        LVname = new javax.swing.JTextField();
        removeLVA = new javax.swing.JButton();
        AddLVA = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LVtable = new javax.swing.JTable();
        LVfehlertext = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        MN4 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        SzLtable = new javax.swing.JTable();
        Name4 = new javax.swing.JLabel();
        StudentAnmelden = new javax.swing.JButton();
        StudentAbmelden = new javax.swing.JButton();
        StudentSchauwen = new javax.swing.JButton();
        combo = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        LVfehlertext4 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        DzLtc = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox();
        Dabmelden = new javax.swing.JButton();
        Dzuweisen = new javax.swing.JButton();
        Dschauen = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        DzLtable = new javax.swing.JTable();
        DzLname = new javax.swing.JLabel();
        DzLtext = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        combo3 = new javax.swing.JComboBox();
        Listen = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        ListeS = new javax.swing.JTable();
        LV5name = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ListeD = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LVAtap.setBackground(new java.awt.Color(204, 255, 255));
        LVAtap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Mtrikelnummer:");

        jLabel2.setText("Name:");

        jLabel3.setText("Nachname:");

        jLabel4.setText("Adress:");

        jLabel5.setText("id:");

        jLabel6.setText("Telefonnummer:");

        jLabel7.setText("email:");

        jLabel8.setText("Geburtstag:");

        jLabel9.setText("Geburtsort:");

        jLabel10.setText("Fachbereich:");

        Studentliste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrikelnummer", "Name", "Nachname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Studentliste);

        loascheS.setText("Student loaschen");
        loascheS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loascheSActionPerformed(evt);
            }
        });

        Addstudent.setText("Student hizufugen");
        Addstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddstudentActionPerformed(evt);
            }
        });

        Fehlertext.setForeground(new java.awt.Color(0, 255, 51));

        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("Alles mit (*) muss gefült werden ");

        clear1.setText("Clear filds");
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });

        jLabel36.setForeground(new java.awt.Color(255, 51, 0));
        jLabel36.setText("*");

        jLabel37.setForeground(new java.awt.Color(255, 51, 0));
        jLabel37.setText("*");

        jLabel38.setForeground(new java.awt.Color(255, 51, 0));
        jLabel38.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(loascheS, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Addstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Adress, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Telefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Geburtstag, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Geburtsort, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fachbereich, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(85, 85, 85)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Nachname, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MN, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(Fehlertext, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(Adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(Telefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Geburtstag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Geburtsort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Fachbereich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Addstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loascheS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(clear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fehlertext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        LVAtap.addTab("STUDENTEN", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel12.setText("TC nummer:");

        jLabel13.setText("Name:");

        jLabel14.setText("Nachname:");

        jLabel15.setText("AkadimischerTitel:");

        jLabel16.setText("Adress:");

        jLabel17.setText("Telefonnummer:");

        jLabel18.setText("Email:");

        jLabel19.setText("Geburtstag:");

        jLabel20.setText("Geburtsort:");

        Dloaschen.setText("Dozent loaschen");
        Dloaschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DloaschenActionPerformed(evt);
            }
        });

        Dhinzufugen.setText("Dozent hinzufugen");
        Dhinzufugen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DhinzufugenActionPerformed(evt);
            }
        });

        Dtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC nummer", "Name", "Nachname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Dtabel);

        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jLabel21.setText("Alles mit (*) muss gefült werden ");

        Dfehlertext.setForeground(new java.awt.Color(0, 255, 51));

        jLabel22.setText("id:");

        clear2.setText("Clear filds");
        clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2ActionPerformed(evt);
            }
        });

        jLabel39.setForeground(new java.awt.Color(255, 51, 0));
        jLabel39.setText("*");

        jLabel40.setForeground(new java.awt.Color(255, 51, 0));
        jLabel40.setText("*");

        jLabel41.setForeground(new java.awt.Color(255, 51, 0));
        jLabel41.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Dloaschen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Dhinzufugen, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addComponent(Dfehlertext, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel21)
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TCnummer)
                            .addComponent(Dname)
                            .addComponent(Dnachname)
                            .addComponent(Akadimischeritel)
                            .addComponent(Dadress)
                            .addComponent(Dtelefon)
                            .addComponent(Demail)
                            .addComponent(Dgeburtstag)
                            .addComponent(Dgeburtsort)
                            .addComponent(Did, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TCnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Dname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel40)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Dnachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(Akadimischeritel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(Dadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(Dtelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Demail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(Dgeburtstag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(Dgeburtsort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(Did, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Dloaschen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Dhinzufugen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Dfehlertext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LVAtap.addTab("DOZENTEN", jPanel2);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel23.setText("Lehrveranstaltungskürzels:");

        jLabel24.setText("Lehrveranstaltungsname:");

        removeLVA.setText("LVA loaschen");
        removeLVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLVAActionPerformed(evt);
            }
        });

        AddLVA.setText("LVA hinzufugen");
        AddLVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLVAActionPerformed(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 51, 51));
        jLabel25.setText("Alles mit (*) muss gefült werden ");

        LVtable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LVtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kurtzl", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(LVtable);

        LVfehlertext.setForeground(new java.awt.Color(51, 255, 51));

        jLabel42.setForeground(new java.awt.Color(255, 51, 0));
        jLabel42.setText("*");

        jLabel43.setForeground(new java.awt.Color(255, 51, 0));
        jLabel43.setText("*");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(LVfehlertext, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(removeLVA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(AddLVA, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LVname, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LVcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43))))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(LVcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(LVname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel25)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeLVA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddLVA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(LVfehlertext, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        LVAtap.addTab("LVA", jPanel4);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel26.setText("Mtrikelnummer");

        SzLtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LVA kurzel", "LVA name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(SzLtable);

        Name4.setForeground(new java.awt.Color(0, 255, 255));

        StudentAnmelden.setText("Anmelden");
        StudentAnmelden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentAnmeldenActionPerformed(evt);
            }
        });

        StudentAbmelden.setText("Abmelden");
        StudentAbmelden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentAbmeldenActionPerformed(evt);
            }
        });

        StudentSchauwen.setText("Student schauen");
        StudentSchauwen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentSchauwenActionPerformed(evt);
            }
        });

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        jLabel27.setText("LVA kurzel");

        LVfehlertext4.setForeground(new java.awt.Color(51, 255, 102));

        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("Alles mit (*) muss gefült werden ");

        jLabel32.setText("Liste von :");

        jLabel44.setForeground(new java.awt.Color(255, 0, 0));
        jLabel44.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(MN4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel44)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(StudentAbmelden, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StudentAnmelden, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LVfehlertext4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(29, 29, 29))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(StudentSchauwen)))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(Name4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Name4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel31)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentAbmelden, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentAnmelden, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(StudentSchauwen)
                        .addGap(35, 35, 35)
                        .addComponent(LVfehlertext4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        LVAtap.addTab("Student zur LVA", jPanel3);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel28.setText("TC nummer*");

        jLabel29.setText("LVA kurzel");

        Dabmelden.setText("Abmelden");
        Dabmelden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DabmeldenActionPerformed(evt);
            }
        });

        Dzuweisen.setText("Zuweisen");
        Dzuweisen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DzuweisenActionPerformed(evt);
            }
        });

        Dschauen.setText("Dozent schauen");
        Dschauen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DschauenActionPerformed(evt);
            }
        });

        DzLtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LVA kurzel", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(DzLtable);

        DzLname.setForeground(new java.awt.Color(0, 255, 255));

        DzLtext.setForeground(new java.awt.Color(51, 255, 51));

        jLabel33.setText("Liste von :");

        jLabel35.setForeground(new java.awt.Color(255, 0, 0));
        jLabel35.setText("Alles mit (*) muss gefült werden ");

        jLabel45.setForeground(new java.awt.Color(255, 51, 0));
        jLabel45.setText("*");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Dabmelden, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(Dzuweisen, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DzLtext, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(Dschauen, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel35)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(DzLtc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel45)
                                        .addGap(38, 38, 38)
                                        .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel28)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel29)))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DzLname, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DzLname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DzLtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel35)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dabmelden, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dzuweisen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(Dschauen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(DzLtext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        LVAtap.addTab("Dozent zu LVA", jPanel5);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jLabel30.setText("LVA kurzel");

        Listen.setText("Schauen");
        Listen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListenActionPerformed(evt);
            }
        });

        ListeS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrikelnummer", "Name", "Nachname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(ListeS);

        LV5name.setForeground(new java.awt.Color(0, 255, 255));

        ListeD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC nummer", "Name", "Nachname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(ListeD);

        jLabel34.setText("Liste von :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel30))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(combo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Listen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LV5name, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LV5name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel30)
                        .addGap(37, 37, 37)
                        .addComponent(combo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Listen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        LVAtap.addTab("LVA LISTEN", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LVAtap, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(LVAtap, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddstudentActionPerformed

        String ma = MN.getText();
        String n = Name.getText();
        String nn = Nachname.getText();
        if (Student.istGueltig(ma) == 1 | Student.istGueltig(ma) == 2) {
            JOptionPane.showMessageDialog(jPanel1, "Falsche Matrikelnummer", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);

        } else if (Student.istGueltig(ma) == 3) {
            JOptionPane.showMessageDialog(jPanel1, "Falsche Matrikelnummer", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (uni.checkStudent(ma)) {
            JOptionPane.showMessageDialog(jPanel1, "Matrikelnummer schon existiert", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);

        } else if (n.isEmpty() == true | nn.isEmpty() == true) {
            JOptionPane.showMessageDialog(jPanel1, "Falsche Name oder Nachname", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);

        } else if (n.length() > 20 | nn.length() > 20) {
            JOptionPane.showMessageDialog(jPanel1, "lange Name oder Nachname", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {

            String ad = Adress.getText();
            String id = Id.getText();
            String tel = Telefonnummer.getText();
            String em = Email.getText();
            String go = Geburtsort.getText();
            String gt = Geburtstag.getText();
            String fa = Fachbereich.getText();
            Student s = new Student(ma, n, nn, ad, id, tel, em, go, gt, fa);
            uni.StudentHinzufugen(s);
            String[] ss = new String[3];
            ss[0] = s.getMatrikelnummer();
            ss[1] = s.getName();
            ss[2] = s.getNachname().toUpperCase();
            Fehlertext.setText("Erfolgreich hinzugefügt");
            DefaultTableModel dtm = (DefaultTableModel) Studentliste.getModel();
            dtm.addRow(ss);

        }

    }//GEN-LAST:event_AddstudentActionPerformed

    private void loascheSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loascheSActionPerformed
        int i = Studentliste.getSelectedRow();
        if (i >= 0) {
            String ma = (String) Studentliste.getModel().getValueAt(i, 0);
            uni.StudentLoeschen(ma);
            ((DefaultTableModel) Studentliste.getModel()).removeRow(i);

            Fehlertext.setText("Erfolgreich gelöscht");
        }

    }//GEN-LAST:event_loascheSActionPerformed

    private void DhinzufugenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DhinzufugenActionPerformed
        String tc = TCnummer.getText();
        String n = Dname.getText();
        String nn = Dnachname.getText();
        boolean j = false;
        if (Dozent.istGueltig(tc) == 1 | Dozent.istGueltig(tc) == 2) {
            JOptionPane.showMessageDialog(jPanel2, "Falsche TC nummer", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (n.isEmpty() == true | nn.isEmpty() == true) {
            JOptionPane.showMessageDialog(jPanel2, "Falsche Name oder Nachname", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (n.length() > 20 | nn.length() > 20) {
            JOptionPane.showMessageDialog(jPanel2, "lange Name oder Nachname", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (j) {
            JOptionPane.showMessageDialog(jPanel1, "TC nummer schon existiert", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            String ad = Dadress.getText();
            String ak = Akadimischeritel.getText();
            String tel = Dtelefon.getText();
            String em = Demail.getText();
            String go = Dgeburtsort.getText();
            String gt = Dgeburtstag.getText();
            String did = Did.getText();

            Dozent d = new Dozent(tc, n, nn, ak, ad, did, tel, em, go, gt);
            uni.Dozent_einfugen(d);
            String[] dd = new String[3];
            dd[0] = d.getTC_nummer();
            dd[1] = d.getName();
            dd[2] = d.getNachname().toUpperCase();
            Dfehlertext.setText("Erfolgreich hinzugefügt");
            DefaultTableModel dtm1 = (DefaultTableModel) Dtabel.getModel();
            dtm1.addRow(dd);
        }
    }//GEN-LAST:event_DhinzufugenActionPerformed

    private void DloaschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DloaschenActionPerformed
        int i = Dtabel.getSelectedRow();
        if (i >= 0) {
            String tc = (String) Dtabel.getModel().getValueAt(i, 0);
            uni.dozent_Loschen(tc);
            ((DefaultTableModel) Dtabel.getModel()).removeRow(i);

            Dfehlertext.setText("Erfolgreich gelöscht");
        }
    }//GEN-LAST:event_DloaschenActionPerformed

    private void AddLVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLVAActionPerformed
        String ku = LVcode.getText();
        String n = LVname.getText();

        if (LV.istGueltig(ku) == 1 | LV.istGueltig(ku) == 2) {
            JOptionPane.showMessageDialog(jPanel3, "Falsche Lehrveranstaltungskürzel", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (n.isEmpty() == true | n.length() > 20) {
            JOptionPane.showMessageDialog(jPanel3, "Falsche  oder lange Name", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (uni.check_LV(ku)) {
            JOptionPane.showMessageDialog(jPanel3, "Lehrveranstaltung schon existiert", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            LV l = new LV(ku, n);
            uni.LV_einfugen(l);
            String[] cd = new String[2];
            cd[0] = l.getCode();
            cd[1] = l.getName();

            LVfehlertext.setText("Erfolgreich hinzugefügt");
            DefaultTableModel dtm2 = (DefaultTableModel) LVtable.getModel();
            dtm2.addRow(cd);

            combo.addItem(l.getCode());
            combo2.addItem(l.getCode());
            combo3.addItem(l.getCode());
        }
    }//GEN-LAST:event_AddLVAActionPerformed

    private void removeLVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLVAActionPerformed

        int i = LVtable.getSelectedRow();
        if (i >= 0) {
            String ku = (String) LVtable.getModel().getValueAt(i, 0);
            uni.LVALoeschen(ku);
            ((DefaultTableModel) LVtable.getModel()).removeRow(i);
            combo.removeItemAt(i);
            combo2.removeItemAt(i);
            combo3.removeItemAt(i);
            LVfehlertext.setText("Erfolgreich gelöscht");
        }
    }//GEN-LAST:event_removeLVAActionPerformed

    private void StudentSchauwenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentSchauwenActionPerformed
        String ma = MN4.getText();
        if (uni.checkStudent(ma) == false) {
            JOptionPane.showMessageDialog(jPanel3, "ungultige Matrikelnummer oder existiert nicht einen Student mit diesem Matrikelnummer", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {

            DefaultTableModel dtm3 = (DefaultTableModel) SzLtable.getModel();
            dtm3.setRowCount(0);
            Student s1 = new Student(ma);
            int i = 0;
            for (i = 0; i < uni.getStudenten().size(); i++) {
                Student s2 = uni.getStudenten().elementAt(i);
                if (s2.getMatrikelnummer().compareTo(s1.getMatrikelnummer()) == 0) {

                    break;
                }
            }
            Student s3 = uni.getStudenten().elementAt(i);
            Name4.setText(s3.toString());
            Vector<LV> l = uni.getStudenten().get(i).getAngemeldeteLV();
            if (l.size() == 0) {
                JOptionPane.showMessageDialog(jPanel3, "Student hat keine LVA", "Fehler",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            for (int k = 0; k < l.size(); k++) {
                String[] lv = new String[2];
                lv[0] = l.get(k).getCode();
                lv[1] = l.get(k).getName();
                dtm3.addRow(lv);
            }

        }
    }//GEN-LAST:event_StudentSchauwenActionPerformed

    private void StudentAbmeldenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentAbmeldenActionPerformed
        String ma = MN4.getText();
        if (uni.checkStudent(ma) == false) {
            JOptionPane.showMessageDialog(jPanel3, "ungultige Matrikelnummer oder existiert nicht einen Student mit diesem Matrikelnummer", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            int i = SzLtable.getSelectedRow();
            if (i >= 0) {
                String co = (String) SzLtable.getModel().getValueAt(i, 0);
                uni.StudentVonLvaAbmelden(co, ma);
                ((DefaultTableModel) SzLtable.getModel()).removeRow(i);

                LVfehlertext4.setText("Erfolgreich gelöscht");
            }
        }
    }//GEN-LAST:event_StudentAbmeldenActionPerformed

    private void StudentAnmeldenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentAnmeldenActionPerformed
        String ma = MN4.getText();
        if (uni.checkStudent(ma) == false) {
            JOptionPane.showMessageDialog(jPanel3, "ungultige Matrikelnummer oder existiert nicht einen Student mit diesem Matrikelnummer", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            Object o = combo.getSelectedItem();
            Student s1 = new Student(ma);
            int k = 0;
            for (k = 0; k < uni.getStudenten().size(); k++) {
                Student s2 = uni.getStudenten().elementAt(k);
                if (s2.getMatrikelnummer().compareTo(s1.getMatrikelnummer()) == 0) {
                    break;
                }
            }
            Student s3 = uni.getStudenten().elementAt(k);
            Vector<LV> l1 = uni.getStudenten().get(k).getAngemeldeteLV();
            boolean u = false;
            for (int r = 0; r < l1.size(); r++) {
                if (l1.get(r).getCode() == (String) o) {
                    u = true;
                    break;
                }
            }

            if (u) {
                JOptionPane.showMessageDialog(jPanel3, "Lehrveranstaltung schon existiert", "Fehler",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {

                DefaultTableModel dtm3 = (DefaultTableModel) SzLtable.getModel();
                dtm3.setRowCount(0);
                LV l = new LV((String) o);
                int i = 0;
                LV l2 = new LV();
                for (i = 0; i < uni.getLVs().size(); i++) {
                    l2 = uni.getLVs().elementAt(i);
                    if (l2.getCode().compareTo(l.getCode()) == 0) {
                        break;
                    }
                }

                uni.LVZuStudent(l2.getCode(), ma);

                Name4.setText(s3.toString());

                for (int j = 0; j < l1.size(); j++) {
                    String[] lv = new String[2];
                    lv[0] = l1.get(j).getCode();
                    lv[1] = l1.get(j).getName();
                    dtm3.addRow(lv);
                }
                LVfehlertext4.setText("Erfolgreich hinzugefügt");
            }
        }
    }//GEN-LAST:event_StudentAnmeldenActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void DzuweisenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DzuweisenActionPerformed
        String tc = DzLtc.getText();
        boolean t = false;
        int y;

        for (y = 0; y < Dtabel.getRowCount(); y++) {
            if (tc.equals((String) Dtabel.getValueAt(y, 0))) {
                t = true;
                break;
            }
        }
        if (t == false) {
            JOptionPane.showMessageDialog(jPanel3, "ungultige TC nummer oder existiert nicht einen Dozent mit diesem TC nummer", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            Object o = combo2.getSelectedItem();
            Dozent d1 = new Dozent(tc);
            int k = 0;
            for (k = 0; k < uni.getDozenten().size(); k++) {
                Dozent d2 = uni.getDozenten().elementAt(k);
                if (d2.getTC_nummer().compareTo(d1.getTC_nummer()) == 0) {
                    break;
                }
            }
            Dozent d3 = uni.getDozenten().elementAt(k);
            Vector<LV> l1 = uni.getDozenten().get(k).getZugewieseneLV();
            boolean u = false;
            for (int r = 0; r < l1.size(); r++) {
                if (l1.get(r).getCode() == (String) o) {
                    u = true;
                    break;
                }
            }
             if (u) {
            JOptionPane.showMessageDialog(jPanel3, "Lehrveranstaltung schon existiert", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {

            DefaultTableModel dtm3 = (DefaultTableModel) DzLtable.getModel();
            dtm3.setRowCount(0);
            LV l = new LV((String) o);
            int i = 0;
            LV l2 = new LV();
            for (i = 0; i < uni.getLVs().size(); i++) {
                l2 = uni.getLVs().elementAt(i);
                if (l2.getCode().compareTo(l.getCode()) == 0) {
                    break;
                }
            }

            uni.DozentZurLvazuweisen(l2.getCode(), tc);

            DzLname.setText(d3.getName() + "  " + d3.getNachname().toUpperCase());

            for (int j = 0; j < l1.size(); j++) {
                String[] lv = new String[2];
                lv[0] = l1.get(j).getCode();
                lv[1] = l1.get(j).getName();
                dtm3.addRow(lv);
            }
            DzLtext.setText("Erfolgreich zugewiesen");
        }
        }
    }//GEN-LAST:event_DzuweisenActionPerformed

    private void DabmeldenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DabmeldenActionPerformed
        String tc = DzLtc.getText();
        boolean t = false;
        int y;

        for (y = 0; y < Dtabel.getRowCount(); y++) {
            if (tc.equals((String) Dtabel.getValueAt(y, 0))) {
                t = true;
                break;
            }
        }
        if (t == false) {
            JOptionPane.showMessageDialog(jPanel3, "ungultige TC nummer oder existiert nicht einen Dozent mit diesem TC nummer", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            int i = DzLtable.getSelectedRow();
            if (i >= 0) {
                String co = (String) DzLtable.getModel().getValueAt(i, 0);
                uni.DozentVonLvaAbmelden(co, tc);
                ((DefaultTableModel) DzLtable.getModel()).removeRow(i);

                DzLtext.setText("Erfolgreich gelöscht");
            }
        }
    }//GEN-LAST:event_DabmeldenActionPerformed

    private void DschauenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DschauenActionPerformed
        String tc = DzLtc.getText();
        boolean t = false;
        int y;

        for (y = 0; y < Dtabel.getRowCount(); y++) {
            if (tc.equals((String) Dtabel.getValueAt(y, 0))) {
                t = true;
                break;
            }
        }
        if (t == false) {
            JOptionPane.showMessageDialog(jPanel3, "ungultige TC nummer oder existiert nicht einen Dozent mit diesem TC nummer", "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {

            DefaultTableModel dtm3 = (DefaultTableModel) DzLtable.getModel();
            dtm3.setRowCount(0);
            Dozent d1 = new Dozent(tc);
            int i = 0;
            for (i = 0; i < uni.getDozenten().size(); i++) {
                Dozent d2 = uni.getDozenten().elementAt(i);
                if (d2.getTC_nummer().compareTo(d1.getTC_nummer()) == 0) {

                    break;
                }
            }
            Dozent d3 = uni.getDozenten().elementAt(i);
            DzLname.setText(d3.getName()+"  "+d3.getNachname().toUpperCase());
            Vector<LV> l = uni.getDozenten().get(i).getZugewieseneLV();
            if (l.size() == 0) {
                JOptionPane.showMessageDialog(jPanel3, "Dozent hat keine LVA", "Fehler",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            for (int k = 0; k < l.size(); k++) {
                String[] lv = new String[2];
                lv[0] = l.get(k).getCode();
                lv[1] = l.get(k).getName();
                dtm3.addRow(lv);
            }

        }
    }//GEN-LAST:event_DschauenActionPerformed

    private void ListenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListenActionPerformed
        Object o = combo3.getSelectedItem();
        DefaultTableModel dtm3 = (DefaultTableModel) ListeS.getModel();
            dtm3.setRowCount(0);
        DefaultTableModel dtm2 = (DefaultTableModel) ListeD.getModel();
            dtm2.setRowCount(0);
        LV l =new LV((String)o);
            int i = 0;
            for (i = 0; i < uni.getLVs().size(); i++) {
                LV l2 = uni.getLVs().elementAt(i);
                if (l2.getCode().compareTo(l.getCode()) == 0) {

                    break;
                }
            }
            LV l3 = uni.getLVs().elementAt(i);
            LV5name.setText(l3.getCode()+"  "+l3.getName().toUpperCase());
            Vector<Dozent> d = uni.getLVs().get(i).getZugewieseneDozenten();
            Vector<Student> s = uni.getLVs().get(i).getAngemeldeteStudenten();
            
            for (int k = 0; k < s.size(); k++) {
                String[] st = new String[3];
                st[0] = s.get(k).getMatrikelnummer();
                st[1] = s.get(k).getName();
                st[2] = s.get(k).getNachname().toUpperCase();
                dtm3.addRow(st);
            }
            for (int q = 0; q< d.size(); q++) {
                String[] dt = new String[3];
                dt[0] = d.get(q).getTC_nummer();
                dt[1] = d.get(q).getName();
                dt[2] = d.get(q).getNachname().toUpperCase();
                dtm2.addRow(dt);
            }
    }//GEN-LAST:event_ListenActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        MN.setText("");
        Name.setText("");
        Nachname.setText("");
        Id.setText("");
        Adress.setText("");
        Email.setText("");
        Geburtstag.setText("");
        Geburtsort.setText("");
        Fachbereich.setText("");
        Telefonnummer.setText("");
    }//GEN-LAST:event_clear1ActionPerformed

    private void clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2ActionPerformed
        Akadimischeritel.setText("");
        TCnummer.setText("");
        Dname.setText("");
        Dnachname.setText("");
        Dtelefon.setText("");
        Demail.setText("");
        Did.setText("");
        Dgeburtstag.setText("");
        Dgeburtsort.setText("");
        Dadress.setText("");
    }//GEN-LAST:event_clear2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLVA;
    private javax.swing.JButton Addstudent;
    private javax.swing.JTextField Adress;
    private javax.swing.JTextField Akadimischeritel;
    private javax.swing.JButton Dabmelden;
    private javax.swing.JTextField Dadress;
    private javax.swing.JTextField Demail;
    private javax.swing.JLabel Dfehlertext;
    private javax.swing.JTextField Dgeburtsort;
    private javax.swing.JTextField Dgeburtstag;
    private javax.swing.JButton Dhinzufugen;
    private javax.swing.JTextField Did;
    private javax.swing.JButton Dloaschen;
    private javax.swing.JTextField Dnachname;
    private javax.swing.JTextField Dname;
    private javax.swing.JButton Dschauen;
    private javax.swing.JTable Dtabel;
    private javax.swing.JTextField Dtelefon;
    private javax.swing.JLabel DzLname;
    private javax.swing.JTable DzLtable;
    private javax.swing.JTextField DzLtc;
    private javax.swing.JLabel DzLtext;
    private javax.swing.JButton Dzuweisen;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Fachbereich;
    private javax.swing.JLabel Fehlertext;
    private javax.swing.JTextField Geburtsort;
    private javax.swing.JTextField Geburtstag;
    private javax.swing.JTextField Id;
    private javax.swing.JLabel LV5name;
    private javax.swing.JTabbedPane LVAtap;
    private javax.swing.JTextField LVcode;
    private javax.swing.JLabel LVfehlertext;
    private javax.swing.JLabel LVfehlertext4;
    private javax.swing.JTextField LVname;
    private javax.swing.JTable LVtable;
    private javax.swing.JTable ListeD;
    private javax.swing.JTable ListeS;
    private javax.swing.JButton Listen;
    private javax.swing.JTextField MN;
    private javax.swing.JTextField MN4;
    private javax.swing.JTextField Nachname;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel Name4;
    private javax.swing.JButton StudentAbmelden;
    private javax.swing.JButton StudentAnmelden;
    private javax.swing.JButton StudentSchauwen;
    private javax.swing.JTable Studentliste;
    private javax.swing.JTable SzLtable;
    private javax.swing.JTextField TCnummer;
    private javax.swing.JTextField Telefonnummer;
    private javax.swing.JButton clear1;
    private javax.swing.JButton clear2;
    private javax.swing.JComboBox combo;
    private javax.swing.JComboBox combo2;
    private javax.swing.JComboBox combo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton loascheS;
    private javax.swing.JButton removeLVA;
    // End of variables declaration//GEN-END:variables

}
